### ISSUE TITLE
JS error on /events prevents loading events list

### ISSUE THREAD

**Issue by lenareinhard** [hoodiehq/hood.ie#204]
Uncaught TypeError: eventItem.date.getTime is not a function
in events.js:138

Events list is not loading anymore now. 
![image](https://cloud.githubusercontent.com/assets/3472712/10497979/5006e1b8-72c9-11e5-810b-c2b896bafe31.png)

**Comment by zoepage** [comment]
cc @espy :)

**Comment by lewiscowper** [comment]
I've done some digging, and it seems like something somewhere has changed the format of the dates that we're getting. What (I think) we need is `eventItem.date` to be `new Date(yyyy,mm,dd)`, but all we're getting through is `Date(yyyy,mm,dd)` and because that's a string, getTime is not a function on it. I would love to try and make sense of the code to fix it, but I think someone who's done more work with Sheetrock/the GDoc/this is probably better positioned to do it.

**Comment by espy** [comment]
That seems to have done it :)
