### ISSUE TITLE
Implementation of responsive image solution

### ISSUE THREAD

**Issue by verpixelt** [hoodiehq/hood.ie#31]
Add a responsive image solution.

**Comment by zoepage** [comment]
We did this already, right @verpixelt ?

**Comment by verpixelt** [comment]
Not to my knowledge.

**Comment by zoepage** [comment]
Could you give more information about this topic?

**Comment by verpixelt** [comment]
There is no solution for responsive images implemented, yet. Hood.ie serves the same image to every device. Right now this isn't that big of an issue since we don't have that much (large) images on the page. But keep in mind e.g. using an image on the blog either looks super blurry on retina or is heavy on mobile connections with the current setup.

**Comment by chrisdemars** [comment]
Is this issue still open?

**Comment by espy** [comment]
Yes, but we haven't found a feasible method of serving adaptive images (this is what this is for) from GH-Pages' Jekyll. I've thought about using something like [Imgix](https://www.imgix.com), because it serves different file sizes per device automatically, but I'm not sure whether this is overkill or not, since it also makes adding images more complex. 

If you have any good ideas, let's hear them! :)

**Comment by NickColley** [comment]
You could do an audit of your current images, if there's not too many you could just manually create variable sizes and use `srcset` or `<picture>` etc.
This would remove the need to do any server-side logic / CDN magic.

**Comment by chrisdemars** [comment]
What about using the srcset attributes on the img tag to serve up different size images per resolution?

**Comment by verpixelt** [comment]
I'd close that issue. The most image heavy page we have is our community page and even without any particular image solution this page is still < 800kb.
