### ISSUE TITLE
random underlines for h3 on /animals

### ISSUE THREAD

**Issue by lenareinhard** [hoodiehq/hood.ie#87]
both under "Low-Profile Dog" and "Coming soon …", I have no explanation; couldn't find the issue on another page and couldn't reproduce; suppose it's related with the styles for lilac 

![screen shot 2014-11-10 at 22 54 54](https://cloud.githubusercontent.com/assets/3472712/4984493/503d1ce2-6924-11e4-8841-b56a989fc653.png)

**Comment by verpixelt** [comment]
I've found the problem, have fixed it but cant't explain it at the moment. Because we use article tags to separate our content we are, according to the HTML5 spec, allowed to use multiple `<h1>` tags on one page. Therefor we have classes like h3 (`<h1 class="h3">headline</h1>`). This results in the same visual output like `<h3>headline</h3>`. Why the underline doesn't behave like it should – I have no clue o_0
I'll push the fix as soon as I have an internet connection.

**Comment by lenareinhard** [comment]
ok, perfect, thanks. (Actually I also tried `<h1 class="h3">headline</h1>`, but hadn't worked for me :) )

**Comment by verpixelt** [comment]
Jep, and you're right about that. Using `<h1 class="h3>` is the proper way to go but wasn't the fix(even if I said so ;P). Adjusting the link background-position for headlines explicitly in FF solved the problem.
