### ISSUE TITLE
Autoprefixer may be a bit too optmistic

### ISSUE THREAD

**Issue by espy** [hoodiehq/hood.ie#93]
I fear we're being to optimistic with the "last 2 releases" setting, I've seen a couple of firefoxes older than 28, and they don't get flexboxes, for example.

**Comment by lenareinhard** [comment]
When discussing the technical setup, it was decided that the website supports the same broswers that Hoodie supports. @zoepage thinks about a solution / approach now.

**Comment by zoepage** [comment]
We decided that we support all the browsers, we also support with hoodie, because they can't develop anything with Hoodie anyway.
https://github.com/hoodiehq/documentation/blob/gh-pages/tutorials/system-requirements-browser-compatibilities-prerequisites-before-getting-started-with-hoodie.md
- Firefox latest stable (v29)
- Chrome latest stable (v34)
- Desktop Safari latest stable (v7)
- Internet Explorer v10+
- Opera latest stable (v21)
- Android 4.3+
- iOS Safari latest stable (v7.1)

After checking Gauges, we know that there is just a handful of users, who use FF 28 and below. 
That's why I'm closing this issue until it get's a urgent problem. ;)

**Comment by espy** [comment]
Cool, thanks for checking the stats!
